### ISSUE TITLE
[feature] 홈플러스 장바구니 엔티티 추가

### ISSUE THREAD

**Issue by hoyeonj981** [hoyeonj981/PriceBasket#11]
### 기능 설명

홈플러스 마트배송 상품에 대한 장바구니 기능을 구현합니다.

### 기능 요구 사항

- 장바구니 엔티티는 장바구니ID. 상품들, 사용자ID, 최종가격, 배달비, 공유 여부로 구성됩니다.
- 장바구니는 상품을 추가, 삭제, 수량 조절이 가능합니다.
- 장바구니는 수정된 상품개수와 가격에 맞춰 최종가격이 결정됩니다.
- 배달비는 4만원 이상일 경우 무료입니다.

### TODO

- [ ] 장바구니ID, 사용자ID, 상품들, 최종가격, 배달비, 공유 여부으로 구성된 장바구니 엔티티 구현
- [ ] 장바구니에 있는 상품 추가, 삭제, 수량 조절 기능 구현
- [ ]  장바구니 현재 상태에 따라 최종 가격 수정 기능 구현
- [ ]  각 필드에 대한 유효성 검사 기능 추가
- [ ]  4만원을 경계로 배달비 추가 및 빼기 기능 구현
