### ISSUE TITLE
자동화 테스트를 위한 Jacoco, Codecov 환경 설정

### ISSUE THREAD

**Issue by hoyeonj981** [hoyeonj981/PriceBasket#3]
### 기능 설명

Jacoco, Codecov, checkstyle를 이용해서 CI 환경 설정.
CI 환경은 github action을 사용.

### 기능 요구 사항

None.

### TODO

- [x] Jacoco, Codecov 환경 설정하기.
- [x] checkstyle 환경 설정
- [x] github action workflows 생성
