### ISSUE TITLE
[refactor] domain, application에서 예외 문서화 및 일관된 규칙 적용

### ISSUE THREAD

**Issue by hoyeonj981** [hoyeonj981/PriceBasket#36]
### 기능 설명

- domain과 application에서 발생하는 예외에 대한 문서화와 일관된 규칙을 적용한다

### 기능 요구 사항

- domain에서 발생하는 예외는 모두 DomainException을 상속한다
- application에서 발생하는 예외는 ApplicationException을 상속한다
- application에서 정의하는 인터페이스는 발생할 수 있는 예외에 대해서 주석으로 남긴다
- 각 계층에서 발생하는 예외는 일관된 규칙을 적용한다 (상세한 규칙은 미정)

### TODO

- [ ] DomainException 구현 및 기존 예외가 상속하도록 변경
- [ ] ApplicationExcpetion 구현 및 기존 예외가 상속하도록 변경
- [ ] application 계층의 인터페이스 문서화 (예외, 기능 등)
- [ ] 각 계층에 발생하는 예외 일관된 규칙 적용 (파라미터, 예외 메시지 형식 등. 아직 미정)
