### ISSUE TITLE
[feature] 상품 엔티티 추가

### ISSUE THREAD

**Issue by hoyeonj981** [hoyeonj981/PriceBasket#6]
### 기능 설명

검색된 상품을 나타내는 도메인 엔티티를 구현합니다.

### 기능 요구 사항

- 상품 엔티티는 상품ID, 상품명, 가격, 카테고리, 브랜드, 이미지 URL으로 구성됩니다.
- 상품 정보가 업데이트되면 해당 항목은 수정됩니다.

### TODO

- [ ] 상품ID, 상품명, 가격, 브랜드, 카테고리, 이미지URL 정보를 가지는 상품 엔티티 생성
- [ ] 각 필드에 대한 유효성 검사 기능 추가
- [ ] 각 필드 정보 업데이트 기능 추가
