### ISSUE TITLE
[feature] 이마트몰, 홈플러스 카테고리 기능 구현

### ISSUE THREAD

**Issue by hoyeonj981** [hoyeonj981/PriceBasket#8]
### 기능 설명

이마트몰과 홈플러스의 상품들과 연관될 카테고리 엔티티를 구현합니다.

### 기능 요구 사항

- 카테고리는 카테고리 ID, 이름을 가져야 하며 중복된 카테고리는 허용하지 않습니다.
- 카테고리와 아이템은 연관관계가 있습니다. (M:N)

### TODO

- [ ] 카테고리ID, 이름을 가지는 카테고리 엔티티 구현하기
- [ ] 각 필드에 대한 유효성 검사 기능 추가
- [ ] 상품 카테고리 연관 관계 구현

**Comment by hoyeonj981** [comment]
#19 와 동일한 이슈
